#!/usr/bin/env sh

# Print color table in 256 color term
# Convert values between RGB hex codes and 256 color term color codes
# By delta4d@gmail.com

FG='\e[38;5;'
BG='\e[48;5;'
RESET='\e[0m'
RGBTable1=('000000' '800000' '008000' '808000' '000080' '800080' '008080' 'c0c0c0'\
	'808080' 'ff0000' '00ff00' 'ffff00' '0000ff' 'ff00ff' '00ffff' 'ffffff')
RGBTable2=('00' 'f5' '78' 'fa' '7d' 'ff')
RGBTable3=('08' '12' '1c' '26' '30' '3a' '44' '4e' '58' '62' '6c' '76' '80' '8a'\
	'94' '9e' 'a8' 'b2' 'bc' 'c6' 'd0' 'da' 'e4' 'ee')
BLACK=0
RED=1
GREEN=2
YELLOW=3
BLUE=4
MAGENTA=5
CYAN=6
WHITE=7
black=8
red=9
green=10
yellow=11
blue=12
magenta=13
cyan=14
white=15

usage() {
	echo -e "Usage: "`basename $0`" [options] [values]\n"
	echo -e "Options:"
	echo -e "  none\t\tprint all 256 colors"
	echo -e "  -x var\tconvert term color value 'var' to RGB value"
	echo -e "  -h\t\tdisplay this and exit"
	exit
}

to_rgb() {
	if (($1 < 16)); then
		echo ${RGBTable1[$1]}
	elif (($1 < 232)); then
		x="$(($1-16))"
		sz="${#RGBTable2[@]}"		
		rgb=
		for i in {0..2}; do
			rgb=$rgb"${RGBTable2[$((x%sz))]}"
			((x/=sz))
		done
		echo $rgb | rev
	else
		x="$(($1-232))"
		echo ${RGBTable3[$x]}{,,} | sed 's/ //g'
	fi
}

output() {
	# $1 background color, $2 foreground color
	echo -en "${BG}${1}m${FG}${2}m`printf "%03d " ${1}`#`to_rgb ${1}`"
}

print_color_table() {
	for i in {0..255}; do
		output $i $BLACK
		((i == 7 || i == 15 || i == 231 || i >= 16 && i % 6 == 237 % 6)) && echo -e "$RESET"
		((i == 15 || i == 231)) && echo -e "$RESET"
		((i < 16 && i % 8 != 7 || i >= 16 && i % 6 != 237 % 6)) && echo -en "$RESET "
	done
}

main() {
	if (($# > 0)); then
		while getopts :x:h opt; do
			case $opt in
				x)	output $OPTARG $BLACK
					echo -e "$RESET";;
				h)	usage;;
				?)	usage;;
			esac
		done
	else
		print_color_table	
	fi
}

main "$@"
